[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "modern-teleport"
dynamic = ["version"]
description = "A modern teleport plugin with rich functional design for Minecraft servers."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "auto-uuid-api-mcdr",
  "location-api",
  "mcdreforged>=2.14.1",
  "moolings-rcon-api",
]

[tool.ruff]
line-length = 79

[tool.hatch.version]
source = "regex"
path = "src/mcdreforged.plugin.json"
pattern = "\"version\"\\s*:\\s*\"(?P<version>[^\"]+)\""

[tool.hatch.build.targets.wheel]
packages = ["src/modern_teleport"]

[tool.uv.sources]
auto-uuid-api-mcdr = { git = "https://github.com/Mooling0602/Auto-UUID-API-MCDR.git" }
location-api = { git = "https://github.com/Mooling0602/LocationAPI-MCDR.git" }
moolings-rcon-api = { git = "https://github.com/Mooling0602/MoolingsRconAPI-MCDR.git" }
